### ISSUE TITLE
[Bug]: Image Picker node implementation interrupts workflow execution unexpectedly

### ISSUE THREAD

**Issue by gshawn3** [yolain/ComfyUI-Easy-Use-Frontend#14]
### Expected Behavior

Workflow execution remains unaffected when users close another browser tab running ComfyUI.

### Actual Behavior

Workflow execution is interrupted whenever users refresh, navigate away, or close another browser tab running ComfyUI.

### Steps to Reproduce

1. Open two tabs pointing to the same instance of ComfyUI
2. In the first tab, run any workflow.
3. While the first workflow is executing, switch to the second tab, and refresh the window. Alternatively, close the tab, or navigate away from the page.
4. Notice that workflow execution is interrupted:

got prompt
 44%|████████████████████████████████████████████████████████████████████▋                                                                                      | 31/70 [00:08<00:10,  3.84it/s]
Processing interrupted
Prompt executed in 8.17 seconds

### Debug Logs

```powershell

```

### Other

First of all, thanks for your hard work on a wonderful suite of nodes and extensions. I realize it must have been a ton of work putting this together.

This issue has been reported a few times, see https://github.com/yolain/ComfyUI-Easy-Use/issues/732 and https://github.com/comfyanonymous/ComfyUI/issues/4014. I added some additional information in the first issue and will just quote it here:

> This is an issue with the Easy-Use integration of the Image Picker node. More specifically, that node registers an event handler that is triggered whenever the browser window is unloaded (or refreshed). This event handler sends a message to ComfyUI to interrupt whatever processing might be happening in the backend.
> 
> I suspect this was done in the original Image Picker node to handle situations when a workflow is paused waiting on users to choose an image, but users refresh the window or navigate away instead. Unfortunately the way it has been carried over into Easy-Use, it now causes the issues we've experienced. It looks like chrisgoringe recently deprecated his Image Picker node entirely in favor or a new Image Filter node, so I'm not sure what is the correct course of action for Easy-Use to take.

The offending line of code is here:
https://github.com/yolain/ComfyUI-Easy-Use-Frontend/blob/e7072b6e9a26ea8c661301923edad013e8e0ced4/src/extensions/imageChooser/chooser.js#L106

**Comment by yolain** [comment]
Thanks for the feedback！You can make it work by disabling the imageChooser extension until i have fixed the issue.

![Image](https://github.com/user-attachments/assets/329a317f-b2e8-4680-9827-b563822e3d56)

**Comment by gshawn3** [comment]
Thanks @yolain, I didn't even know that was an option. Appreciate your prompt reply!!

**Comment by hyupuunos** [comment]
Disabling the imagechooser didn’t solve the problem, and even after upgrading to version 1.2.9, the same issue still persists. Are there any other possible fixes? I’m going crazy over this.
